      PROGRAM RUNJET
      CHARACTER*60 FN
      READ 1000, FN
1000  FORMAT(A)
      PRINT 1020, FN
1020  FORMAT(1X,'Data file      = ',A)
      OPEN(2,FILE=FN,STATUS='NEW',FORM='UNFORMATTED')
      READ 1000, FN
      PRINT 1030, FN
1030  FORMAT(1X,'Parameter file = ',A)
      OPEN(3,FILE=FN,STATUS='OLD',FORM='FORMATTED')
      READ 1000, FN
      PRINT 1040, FN
1040  FORMAT(1X,'Listing file   = ',A)
      OPEN(4,FILE=FN,STATUS='NEW',FORM='FORMATTED')
      READ 1000, FN
      OPEN(1,FILE=FN,STATUS='OLD',FORM='FORMATTED')
      CALL ISAJET(-1,2,3,4)
      STOP
      END
