#!/bin/bash

if [ $# -ne 18 ]; then
         echo Usage: $0 \<mgo\> \<mQL\> \<muR\> \<mdR\> \<mQL3\> \<mtR\> \<mbR\> \<AT\> \<AB\> \<AL\> \<mu\> \<M1\> \<M2\> \<tb\> \<meL\> \<mtauL\> \<meR\> \<mtauR\>  
         exit 127
fi

echo $9
echo ${10}
echo ${11}

SpecStart=Spectrum.in

cat $SpecStart |  awk '{

     if ($1 == "Block") {Block=$2; print $0}

     else if(Block=="EXTPAR" && $1==3)  print " ",$1,'$1'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==41) print " ",$1,'$2'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==42) print " ",$1,'$2'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==44) print " ",$1,'$3'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==45) print " ",$1,'$3'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==47) print " ",$1,'$4'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==48) print " ",$1,'$4'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==43) print " ",$1,'$5'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==46) print " ",$1,'$6'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==49) print " ",$1,'$7'"E+00",$3,$4

     else if(Block=="EXTPAR" && $1==11) print " ",$1,'$8'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==12) print " ",$1,'$9'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==13) print " ",$1,'${10}'"E+00",$3,$4

     else if(Block=="EXTPAR" && $1==23) print " ",$1,'${11}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==1)  print " ",$1,'${12}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==2)  print " ",$1,'${13}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==25) print " ",$1,'${14}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==31) print " ",$1,'${15}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==32) print " ",$1,'${15}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==33) print " ",$1,'${16}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==34) print " ",$1,'${17}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==35) print " ",$1,'${17}'"E+00",$3,$4
     else if(Block=="EXTPAR" && $1==36) print " ",$1,'${18}'"E+00",$3,$4
     else print $0

}'