CDECK  ID>, VISAJE.
      CHARACTER*40 FUNCTION VISAJE()
      COMMON/IDRUN/IDVER,IDG(2),IEVT,IEVGEN
      SAVE /IDRUN/
      INTEGER   IDVER,IDG,IEVT,IEVGEN
      VISAJE = ' ISAJET     V7.80   29-OCT-2009 12:50:36'
      IDVER = 780
      RETURN
      END
